spring:
  application:
    name: inventory-ai
  datasource:
    url: jdbc:mysql://localhost:3306/ai_inventory?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
ai:
  api-key: sk-7de62cff0dcd4422acc25d6cbb5ef7c2
  base-url: https://api.deepseek.com
  model-name: deepseek-chat

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8989